# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ac78d7dd52bd7e11713ac317c1d7bf58c02707dfa0804ecccb5da73be256f0122eee789d49d946b11ffa39a4584a5f4c01c4ea92d97ab12c2055cf3c59f3d0e

test:
  secret_key_base: ed870c519ad7bf5f8ae27b37107424b49195b6dca22508f14e15a2b0e1b5910b1849308732a366915dbe8f223ab7f0ebf7d702cfd79bbc1a376b574f9dc87db4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
